name: Mstupload
version: 0.3.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.7  # 添加file_picker依赖项，并指定版本号
  mysql1: ^0.20.0
  mysql_client: ^0.0.27
  liquid_progress_indicator_v2: ^0.5.0
  process_run: ^1.2.2+1
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  intl: ^0.20.1
  mutex: ^3.1.0
  window_manager: ^0.4.3
  web_socket_channel: ^2.4.0
  uuid: ^3.0.6
  package_info_plus: ^8.3.0

flutter:
  uses-material-design: true