name: Build Windows Application

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest # 使用最新的 Windows 运行环境

    steps:
      # 检出代码
      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/windows/runner/Release
    

      # 设置 Flutter 环境
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1' # 指定 Flutter 版本

      # 新增：动态设置版本号
      - name: Set version from tag or use tmp-test + timestamp
        id: set_version
        run: |
          $manualTrigger = "${{ github.event_name }}" -eq "workflow_dispatch"
          if ($manualTrigger) {
              $version = "tmp-test$(Get-Date -Format 'yyyyMMddHHmm')"
          } else {
              $version = "${{ github.ref_name }}".TrimStart('v')
          }
          Write-Output "VERSION=$version" >> $env:GITHUB_ENV
          
          # 修改 pubspec.yaml 的 version 行
          $pubspecPath = "pubspec.yaml"
          $pubspec = Get-Content -Path $pubspecPath -Raw
          $pubspec = [regex]::Replace($pubspec, '^version: \d+\.\d+\.\d+[\+\d+]?$', "version: $version", [System.Text.RegularExpressions.RegexOptions]::Multiline)
          Set-Content -Path $pubspecPath -Value $pubspec

      # 安装依赖
      - name: Install dependencies
        run: flutter pub get

      # 构建 Windows 应用
      - name: Build Windows application
        run: flutter build windows --release

      # 新增：拷贝必要文件到 Release 目录
      - name: Copy settings and python scripts to Release directory
        run: |
          cp settings-exa.json build/windows/runner/Release/settings.json
          cp requirements.txt lib/web-server.py lib/libfix_for_flutter.py lib/change_for_flutter.py build/windows/runner/Release/

      # 上传构建产物
      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Mstupload-windows-x64-${{ env.VERSION }}
          path: build/windows/runner/Release # Windows 构建产物路径