name: Build Windows Application

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest # 使用最新的 Windows 运行环境

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Flutter 环境
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1' # 指定 Flutter 版本

      # 安装依赖
      - name: Install dependencies
        run: flutter pub get

      # 构建 Windows 应用
      - name: Build Windows application
        run: flutter build windows --release

      # 新增：拷贝必要文件到 Release 目录
      - name: Copy settings and python scripts to Release directory
        run: |
          cp settings-exa.json build/windows/runner/Release/settings.json
          cp requirements.txt lib/web-server.py lib/libfix_for_flutter.py lib/change_for_flutter.py build/windows/runner/Release/

      # 上传构建产物
      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Mstupload-windows-x64-${{ github.ref_name }}
          path: build/windows/runner/Release # Windows 构建产物路径